#!/bin/bash

declare dotFilesDir=$PWD

# Update OS and install dependencies
cd $dotFilesDir/scripts
$dotFilesDir/scripts/setup

# Link configs
cd $dotFilesDir
for dir in $(ls -d */ | grep -v scripts/); do
    cd $dotFilesDir/${dir%/}
    $PWD/setup
done
