#!/bin/sh


# Install packages
sudo apt install -y vim vifm pandoc curl zathura zathura-pdf-poppler texlive-full

# Bootstrap Vim
if command -v vim >/dev/null 2>&1; then
    echo "Bootstrapping Vim"
    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
