#!/bin/bash

# Check for vim
if [[ -z "$(which vim)" || -z "$(which vimtutor)" ]]; then
    echo "Need to install full vim."
    exit 1
fi

# Symbolically link vimrc
ln -sf "$PWD/vimrc" "$HOME/.vimrc"

# Check if macOS
if [[ $OSTYPE == 'darwin'* ]]; then
	echo "Linked $(ls -l -G $HOME/.vimrc | cut -d ' ' -f 10-12)"
else
	echo "Linked $(ls -l --color=auto $HOME/.vimrc | cut -d ' ' -f 10-12)"
fi

read -p "Set vim plugins? (y/n) " response
if [[ $response = y ]]; then
    # Set up vim plugins
    # Should only be run with dependencies installed else it fails
    echo "Setting up Vim..."
    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
    echo "Done!"
else
    echo "Done."
    exit 0
fi

