#!/usr/bin/env zsh

if [[ -z "$(which nvim)" ]]; then
    echo "nvim not installed. Skipping setup."
    exit 1
fi

ln -sfn "$PWD" "$HOME/.config/nvim" 

# check if on macOS
if [[ $OSTYPE == 'darwin'* ]]; then
	echo "Linked $(ls -l -G $HOME/.config/nvim | cut -d ' ' -f 10-12)"
else
	echo "Linked $(ls -l --color=auto $HOME/.config/nvim | cut -d ' ' -f 10-12)"
fi
