#!/usr/bin/env zsh

if [[ -z "$(which zsh)" ]]; then
    echo "zsh not installed. Skipping setup."
    exit 1
fi

ln -sf "$PWD/zshrc" "$HOME/.zshrc"

# check if on macOS
if [[ $OSTYPE == 'darwin'* ]]; then
	echo "Linked $(ls -l -G $HOME/.zshrc | cut -d ' ' -f 10-12)"
else
	echo "Linked $(ls -l --color=auto $HOME/.zshrc | cut -d ' ' -f 10-12)"
fi
