#!/usr/bin/env zsh

if [[ -z "$(which zsh)" ]]; then
    echo "zsh not installed. Skipping setup."
    exit 1
fi


if [[ $OSTYPE == 'darwin'* ]]; then
    ln -sf "$PWD/zshrc" "$HOME/.zshrc"
else
    ln -sf "$PWD/zshrc-kali" "$HOME/.zshrc"
fi

# check if on macOS
if [[ $OSTYPE == 'darwin'* ]]; then
	echo "Linked $(ls -l -G $HOME/.zshrc | tr -s ' ' | cut -d ' ' -f 9-11)"
else
	echo "Linked $(ls -l --color=auto $HOME/.zshrc | cut -d ' ' -f 10-12)"
fi
