#!/usr/bin/env zsh

if [[ -z "$(which zsh)" ]]; then
    echo "zsh not installed. Skipping setup."
    exit 1
fi

read "response?Setup zsh config? (y/n)"
if [[ $response =~ ^[Nn]$ ]]; then
    exit 0
fi

# check if on macOS
if [[ $OSTYPE == 'darwin'* ]]; then
    ln -sf "$PWD/zshrc" "$HOME/.zshrc"
	echo "Linked $(ls -l -G $HOME/.zshrc | tr -s ' ' | cut -d ' ' -f 9-11)"
else
    if grep -iq "kali" /etc/os-release; then
        ln -sf "$PWD/zshrc-kali" "$HOME/.zshrc"
        echo "Linked $(ls -l --color=auto $HOME/.zshrc | cut -d ' ' -f 10-12)"
    elif grep -iq "ubuntu" /etc/os-release; then
        ln -sf "$PWD/zshrc-ubuntu" "$HOME/.zshrc"
        echo "Linked $(ls -l --color=auto $HOME/.zshrc | cut -d ' ' -f 10-12)"
    else
        ln -sf "$PWD/zshrc" "$HOME/.zshrc"
        echo "Linked $(ls -l --color=auto $HOME/.zshrc | cut -d ' ' -f 10-12)"
    fi
fi
